spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect      # DB툴에 맞게 쿼리를 자도응로 바꿔줌
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: create   #DDL 데이터 정의어 : 데이터 구조를 만드는 쿼리문 자동 정의(태이블생성필요없음)

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace